plugins:
  - rubocop-rails
require:
  - rubocop-capybara

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.3
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - 'node_modules/**/*'

Style/Documentation:
  Enabled: false

Rails/I18nLocaleTexts:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'config/environments/*.rb'
    - 'config/routes.rb'
    - 'config/initializers/*.rb'

Metrics/MethodLength:
  Max: 15

Layout/LineLength:
  Max: 120
  Exclude:
    - 'config/initializers/*.rb'
