default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: codespace
  password:

development:
  <<: *default
  database: monitorizacion_development

test:
  <<: *default
  database: monitorizacion_test

production:
  <<: *default
  database: monitorizacion_production

production:
  primary: &primary_production
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>
  queue:
    <<: *primary_production
