default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: 127.0.0.1
  port: 5433
  username: postgres
  password: postgres

development:
  <<: *default
  database: monitorizacion_development

test:
  <<: *default
  database: monitorizacion_test

production:
  <<: *default
  database: monitorizacion_production
